// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbsxPLXOiQ82h_2N-g4TIcAEU6SE6gKrc',
    appId: '1:836180116901:web:83d773fe868d9f7d86944c',
    messagingSenderId: '836180116901',
    projectId: 'tabiat-tarihi-firebase',
    authDomain: 'tabiat-tarihi-firebase.firebaseapp.com',
    storageBucket: 'tabiat-tarihi-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ5rFY7fmlzDm7IJVyMxGCC2yBJBYjnY8',
    appId: '1:836180116901:android:d1cbc25814d2c83286944c',
    messagingSenderId: '836180116901',
    projectId: 'tabiat-tarihi-firebase',
    storageBucket: 'tabiat-tarihi-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcwlVNsDrP3EgMx32ktNueScGnP5MvZgg',
    appId: '1:836180116901:ios:be30d47446cfe5e586944c',
    messagingSenderId: '836180116901',
    projectId: 'tabiat-tarihi-firebase',
    storageBucket: 'tabiat-tarihi-firebase.appspot.com',
    iosClientId: '836180116901-bmi0m4bm1pv7rgupabtlm0nn2ji62uiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.tabiatTarihiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcwlVNsDrP3EgMx32ktNueScGnP5MvZgg',
    appId: '1:836180116901:ios:be30d47446cfe5e586944c',
    messagingSenderId: '836180116901',
    projectId: 'tabiat-tarihi-firebase',
    storageBucket: 'tabiat-tarihi-firebase.appspot.com',
    iosClientId: '836180116901-bmi0m4bm1pv7rgupabtlm0nn2ji62uiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.tabiatTarihiApp',
  );
}
